os: linux
sudo: enabled
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
#  - "3.7"


before_install:
  # gcc (gfortran is not there by default, we install all gcc suit just in case)
  - sudo apt-get install gcc
  - sudo apt-get install gfortran

  # keep record of kliff directory
  - export KLIFF_DIR=$PWD


install:
  # kim-api
  - cd $KLIFF_DIR && cd ..
  - wget http://s3.openkim.org/kim-api/kim-api-v2.0.0-beta.1.txz
  - tar xJf kim-api-v2.0.0-beta.1.txz
  - cd kim-api-v2.0.0-beta.1
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd examples
  - make all-user

  # install SW model
  - cd ~/.kim-api/v2_model_drivers/
  - git clone https://github.com/mjwen/Three_Body_Stillinger_Weber__MD_335816936951_003.git
  - cd Three_Body_Stillinger_Weber__MD_335816936951_003
  - git checkout kimapi2.0
  - make
  - cd ~/.kim-api/v2_models/
  - git clone https://github.com/mjwen/Three_Body_Stillinger_Weber_Si__MO_405512056662_004.git
  - cd Three_Body_Stillinger_Weber_Si__MO_405512056662_004
  - git checkout kimapi2.0
  - make

  # neighlist
  - cd $KLIFF_DIR && cd ..
  - git clone https://github.com/mjwen/neighlist.git
  - cd neighlist/python
  - pip install -e .

  # kimpy
  - cd $KLIFF_DIR && cd ..
  - pip install git+https://github.com/mjwen/kimpy.git@master


script:
  - cd $KLIFF_DIR
  - python setup.py install

  - cd tests
  - pytest test_modelparams.py
  - pytest test_set_parameters_and_cutoff.py
  - pytest test_kimcalculator.py

